### ISSUE TITLE
Clean up the UI

### ISSUE THREAD

**Issue by hlac** [lcomiss/COMP313-Team-Comissiong#4]
#3

**Comment by hlac** [comment]
Users can view a greeting with their full name
Users can logoff of their account and returned to the login page
Users can return to the homepage
Users can select the Prescriptions button to go to the Prescriptions page
User can view details of their treatments
User can view details of their treatments

**Comment by lcomiss** [comment]
assigned on 23/02/15

**Comment by lcomiss** [comment]
> Create and add logo to app
> Format screen background, buttons, layout etc
